# Generated by Django 5.1.7 on 2025-04-10 11:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HalfDayTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resign', 'Resign'), ('debarred', 'Debarred')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], unique=True)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RateStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('non billable', 'Non Billable'), ('billable', 'Billable')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('complete', 'Complete'), ('claim_complete', 'Claim Complete'), ('inprocess', 'In Process')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp_registers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('joindate', models.DateField(null=True)),
                ('reportto', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.departmentmaster')),
                ('job_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.jobstatusmaster')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.rolemaster')),
            ],
        ),
        migrations.CreateModel(
            name='emp_logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year_of_passing', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('guidance_phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('father_guidance_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('permanent_address', models.TextField()),
                ('total_leave', models.FloatField()),
                ('balance_leave', models.FloatField(default=0.0)),
                ('used_leave', models.FloatField(default=0.0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('marriage_status', models.CharField(max_length=20, null=True)),
                ('aadhar_no', models.CharField(max_length=12, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('passport', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('job_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.jobstatusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('applicable_gender', models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='All', help_text='Which gender can apply for this leave.', max_length=10)),
                ('payable', models.BooleanField(default=True)),
                ('applicable_marital_status', models.CharField(choices=[('All', 'All'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='All', help_text='Which marital status can apply for this leave.', max_length=10)),
                ('count_holidays', models.BooleanField(default=False, help_text='Should holidays be counted in the leave duration?')),
                ('count_weekends', models.BooleanField(default=False, help_text='Should weekends be counted in the leave duration?')),
                ('applicable_department', models.ForeignKey(blank=True, help_text='Which department can apply for this leave. Leave blank for all.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.departmentmaster')),
                ('specific_employees', models.ManyToManyField(blank=True, help_text='If specified, this leave type will apply only to selected employees.', to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date(2025, 3, 27))),
                ('no_of_days', models.FloatField(default=0.0)),
                ('reason', models.TextField()),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('half_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.halfdaytypemaster')),
                ('approval_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.leavestatusmaster')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.leavetypemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('priority', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.prioritymaster')),
                ('team_members', models.ManyToManyField(related_name='projects', to='staff.member')),
                ('rate_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.ratestatusmaster')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('leader', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.member')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('priority', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.prioritymaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='staff.project')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment', models.ImageField(upload_to='attachments/')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.project')),
            ],
        ),
    ]
