# Generated by Django 5.1.7 on 2025-03-29 18:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_registers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('position', models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=10, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('joindate', models.DateField(null=True)),
                ('reportto', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('marriage_status', models.CharField(max_length=20, null=True)),
                ('aadhar_no', models.CharField(max_length=12, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
                ('religion', models.CharField(max_length=30, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('job_status', models.CharField(choices=[('active', 'Active'), ('resign', 'Resign'), ('debarred', 'Debarred')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='emp_logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('guidance_phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('father_guidance_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('permanent_address', models.TextField()),
                ('total_leave', models.IntegerField(default=0)),
                ('balance_leave', models.IntegerField(default=0)),
                ('used_leave', models.IntegerField(default=0)),
                ('job_status', models.CharField(choices=[('active', 'Active'), ('resign', 'Resign'), ('debarred', 'Debarred')], default='active', max_length=10)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date(2025, 3, 27))),
                ('no_of_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Compensation Leave', 'Compensation Leave'), ('Half Day', 'Half Day')], max_length=20)),
                ('half_day', models.CharField(blank=True, choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=12, null=True)),
                ('reason', models.TextField()),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('leave_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.leaverecord')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('complete', 'Complete'), ('claim_complete', 'Claim Complete'), ('inprocess', 'In Process')], default='pending', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_status', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('non billable', 'Non Billable'), ('billable', 'Billable')], default='fixed', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('team_members', models.ManyToManyField(related_name='projects', to='staff.member')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('complete', 'Complete'), ('claim_complete', 'Claim Complete'), ('inprocess', 'In Process')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('leader', models.CharField(max_length=100)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='staff.project')),
            ],
        ),
    ]
