# Generated by Django 5.1.7 on 2025-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypemaster',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leavetypemaster',
            name='leave_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetypemaster',
            name='leavecode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='halfdaytypemaster',
            name='part',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='jobstatusmaster',
            name='status',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leavestatusmaster',
            name='status',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prioritymaster',
            name='level',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ratestatusmaster',
            name='status',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='role',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='statusmaster',
            name='status',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
