# Generated by Django 5.1.7 on 2025-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_registers',
            old_name='id',
            new_name='emp_id',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='total_leave',
            field=models.FloatField(),
        ),
    ]
