# Generated by Django 5.1.7 on 2025-04-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_leavetypemaster_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetypemaster',
            name='created_on',
        ),
    ]
