# Generated by Django 5.1.7 on 2025-04-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_id_emp_registers_emp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_registers',
            old_name='emp_id',
            new_name='id',
        ),
    ]
