# Generated by Django 5.1.7 on 2025-04-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_emp_id_emp_registers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
