# Generated by Django 5.1.7 on 2025-04-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_project_emp_id_alter_project_pname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeLeaves',
        ),
    ]
