# Generated by Django 5.1.7 on 2025-04-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_leaverecord_approve_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfdayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employeedetail')),
                ('half_day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.halfdaytypemaster')),
            ],
            options={
                'unique_together': {('date', 'emp_id')},
            },
        ),
    ]
