# Generated by Django 5.1.7 on 2025-04-01 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_delete_employeeleaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 1, 12, 42, 14, 298050, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
