# Generated by Django 5.1.7 on 2025-04-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_leaverecord_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment', models.ImageField(upload_to='attachments/')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.project')),
            ],
        ),
    ]
