# Generated by Django 5.1.7 on 2025-04-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_holiday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypemaster',
            name='carry_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetypemaster',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemaster',
            name='max_days_allowed',
            field=models.IntegerField(null=True),
        ),
    ]
