# Generated by Django 5.1.7 on 2025-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_leavetypemaster_carry_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
