# Generated by Django 5.1.7 on 2025-04-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers'),
            preserve_default=False,
        ),
    ]
