# Generated by Django 5.1.7 on 2025-04-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_task_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='balance_leave',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='used_leave',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
