# Generated by Django 5.1.7 on 2025-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_project_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='leave_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
