# Generated by Django 5.1.7 on 2025-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_employeedetail_leave_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypemaster',
            name='end_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='leavetypemaster',
            name='start_from',
            field=models.DateTimeField(null=True),
        ),
    ]
