# Generated by Django 5.1.7 on 2025-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_employeedetail_balance_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='balance_leave',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='used_leave',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='no_of_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
