# Generated by Django 5.1.7 on 2025-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_leavetypemaster_end_from_leavetypemaster_start_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetypemaster',
            name='applicable_department',
        ),
        migrations.AddField(
            model_name='leavetypemaster',
            name='applicable_department',
            field=models.ManyToManyField(blank=True, help_text="Which departments can apply for this leave. Leave blank or select 'All' for all.", to='staff.departmentmaster'),
        ),
    ]
