# Generated by Django 5.1.7 on 2025-04-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_leavetypemaster_applicable_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'emp_id')},
        ),
        migrations.DeleteModel(
            name='HalfdayMaster',
        ),
    ]
