# Generated by Django 5.1.7 on 2025-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
