# Generated by Django 5.1.7 on 2025-04-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_task_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
