# Generated by Django 5.1.7 on 2025-04-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='compensatory_leave',
            field=models.BooleanField(default=False),
        ),
    ]
