# Generated by Django 5.1.7 on 2025-04-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_leaverecord_compensatory_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='compensatory_leave_reason',
            field=models.TextField(null=True),
        ),
    ]
