# Generated by Django 5.2 on 2025-04-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_leaverecord_compensatory_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='document',
            field=models.FileField(null=True, upload_to='leave_documents/'),
        ),
    ]
