# Generated by Django 5.2 on 2025-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_leaverecord_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='half_day',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='half_day',
            field=models.ManyToManyField(blank=True, null=True, to='staff.halfdaytypemaster'),
        ),
    ]
