# Generated by Django 5.1.7 on 2025-04-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveHalfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_day_date', models.DateField()),
                ('half_day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.halfdaytypemaster')),
                ('leave_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='half_day_entries', to='staff.leaverecord')),
            ],
        ),
    ]
