# Generated by Django 5.1.7 on 2025-04-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_leavehalfday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='half_day',
        ),
    ]
