# Generated by Django 5.1.7 on 2025-04-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_remove_leaverecord_half_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavehalfday',
            name='leave_record',
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='halfday',
            field=models.ManyToManyField(related_name='projects', to='staff.leavehalfday'),
        ),
    ]
