# Generated by Django 5.1.7 on 2025-04-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_remove_leavehalfday_leave_record_leaverecord_halfday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='halfday',
        ),
    ]
