# Generated by Django 5.1.7 on 2025-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_remove_leaverecord_halfday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='half_day',
            field=models.ManyToManyField(blank=True, to='staff.leavehalfday'),
        ),
    ]
