# Generated by Django 5.1.7 on 2025-05-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_leaverecord_half_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledgment_date', models.DateField()),
                ('acknowledgment', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], default='agree', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('changed_fields', models.TextField()),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.employeedetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers')),
            ],
        ),
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='handbooks/')),
                ('active_status', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employees', models.ManyToManyField(related_name='handbooks', through='staff.Acknowledgment', to='staff.emp_registers')),
            ],
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='handbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.handbook'),
        ),
    ]
