# Generated by Django 5.1.7 on 2025-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_acknowledgment_employeedetailhistory_handbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
    ]
