# Generated by Django 5.1.7 on 2025-05-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_alter_handbook_end_date_historicaldocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='marriage_status',
        ),
        migrations.RemoveField(
            model_name='historicalemployeedetail',
            name='marriage_status',
        ),
    ]
