# Generated by Django 5.1.7 on 2025-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_remove_employeedetail_marriage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='document_name',
            field=models.CharField(default='handbook', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acknowledgment',
            name='acknowledgment',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], default='Not Acknowladge', max_length=20),
        ),
    ]
