# Generated by Django 5.1.7 on 2025-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_alter_acknowledgment_acknowledgment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('Learning', 'Learning Video'), ('Project Management', 'Project Management'), ('Task Management', 'Task Management'), ('Timesheet', 'Timesheet Management'), ('Leave', 'Leave Management'), ('User Preference', 'User Preference'), ('Exit', 'Exit Management')], max_length=20)),
            ],
        ),
    ]
