# Generated by Django 5.1.7 on 2025-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
