# Generated by Django 5.1.7 on 2025-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='upload_on',
            field=models.DateField(null=True),
        ),
    ]
