# Generated by Django 5.1.7 on 2025-05-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_remove_member_email_remove_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
