# Generated by Django 5.1.7 on 2025-05-22 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_video_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resign_date', models.DateField()),
                ('last_date', models.DateField()),
                ('reason', models.TextField()),
                ('selected_elsewhere', models.BooleanField(default=False)),
                ('bond_over', models.BooleanField(default=False)),
                ('advance_salary', models.BooleanField(default=False)),
                ('dues_pending', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ongoing_projects', models.BooleanField(default=False)),
                ('outstanding_tasks', models.BooleanField(default=False)),
                ('important_contacts', models.BooleanField(default=False)),
                ('update_passwords', models.BooleanField(default=False)),
                ('revoke_access', models.BooleanField(default=False)),
                ('remove_from_payroll', models.BooleanField(default=False)),
                ('update_employee_directory', models.BooleanField(default=False)),
                ('official_resignation_letter', models.BooleanField(default=False)),
                ('last_paycheck_arrangements', models.BooleanField(default=False)),
                ('nda', models.BooleanField(default=False)),
                ('laptop_and_charger', models.BooleanField(default=False)),
                ('mouse', models.BooleanField(default=False)),
                ('exit_interview_conducted', models.BooleanField(default=False)),
                ('send_announcement', models.BooleanField(default=False)),
                ('give_farewell_party', models.BooleanField(default=False)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='staff.resignation')),
            ],
        ),
    ]
