# Generated by Django 5.1.7 on 2025-05-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_designationmaster_resignation_actionchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_registers',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.designationmaster'),
        ),
        migrations.AddField(
            model_name='historicalemp_registers',
            name='designation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.designationmaster'),
        ),
    ]
