# Generated by Django 5.1.7 on 2025-05-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_resignationstatusmaster_resignstatusaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='resign_status',
            field=models.ForeignKey( on_delete=django.db.models.deletion.DO_NOTHING, to='staff.resignationstatusmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resignation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.emp_registers'),
        ),
    ]
