# Generated by Django 5.1.7 on 2025-05-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_resignation_resign_status_alter_resignation_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='resign_status',
        ),
        migrations.RemoveField(
            model_name='resignstatusaction',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='resignstatusaction',
            name='action_by',
        ),
        migrations.DeleteModel(
            name='ActionChecklist',
        ),
        migrations.DeleteModel(
            name='ResignationStatusMaster',
        ),
        migrations.DeleteModel(
            name='Resignation',
        ),
        migrations.DeleteModel(
            name='ResignStatusAction',
        ),
    ]
