# Generated by Django 5.2.1 on 2025-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0043_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_registers',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp_registers',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalemp_registers',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemp_registers',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
