# Generated by Django 5.2.1 on 2025-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0044_emp_registers_account_locked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(choices=[('success', 'Success'), ('danger', 'Danger'), ('secondary', 'Secondary')], max_length=20)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
