# Generated by Django 5.2.1 on 2025-06-13 07:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0047_payslip_paid_leave_payslip_present_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='CONVENCE_ALLOWANCE',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
