# Generated by Django 5.2.1 on 2025-06-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0048_payslip_convence_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.emp_registers'),
        ),
    ]
