# Generated by Django 5.2.1 on 2025-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0051_latestpayslip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='guidance_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeedetail',
            name='guidance_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeedetail',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
