# Generated by Django 5.2.1 on 2025-07-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0053_chatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user/employee', max_length=255)),
                ('skills_json', models.TextField(blank=True, default='[]', help_text='JSON array of skills')),
                ('projects_json', models.TextField(blank=True, default='[]', help_text='JSON array of projects')),
                ('experiences_json', models.TextField(blank=True, default='[]', help_text='JSON array of experiences')),
                ('ratings_json', models.TextField(blank=True, default='[]', help_text='JSON array of ratings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.emp_registers')),
            ],
        ),
    ]
