# Generated by Django 5.2.1 on 2025-07-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0055_userprofile_role_feedback_skillrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role or designation of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.designationmaster'),
        ),
    ]
