# Generated by Django 5.1.7 on 2025-03-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('remember_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('remail', models.EmailField(max_length=254, unique=True)),
                ('rpassword', models.CharField(max_length=128)),
                ('admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='registers_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('remail', models.EmailField(max_length=254, unique=True)),
                ('rpassword', models.CharField(max_length=128)),
                ('admin', models.BooleanField(default=True)),
            ],
        ),
    ]
